import {
  doc,
  setDoc,
  getDoc,
  updateDoc,
  deleteDoc,
  collection,
  query,
  where,
  orderBy,
  getDocs,
  Timestamp,
} from "firebase/firestore";
import { db } from "./firebase";

// Types

/**
 * Interface representing an individual interview question and candidate answer record.
 * Stored inside the `questions` array in the Firebase Firestore `interviews` collection.
 */
export interface InterviewQuestion {
  /** Unique ID for the question (e.g., "q-1") */
  id: string;
  /** The question text generated by AI or selected from pool */
  text: string;
  /** Candidate's spoken response extracted from interview transcript */
  userAnswer?: string;
  /** Evaluation rating assigned to candidate's response */
  rating?: string;
  /** Targeted coaching feedback specific to this question */
  feedback?: string;
}

/**
 * Structured breakdown of per-question analysis returned by Gemini feedback.
 */
export interface QuestionAnalysis {
  questionId?: string;
  question: string;
  userAnswer: string;
  rating: string;
  feedback: string;
}

/**
 * Complete document schema for an Interview record stored in Firebase Firestore.
 */
export interface Interview {
  id: string;
  userId: string;
  role: string;
  type: string;
  difficulty: string;
  numQuestions: number;
  /** Array of questions along with candidate answers & per-question evaluation */
  questions: InterviewQuestion[];
  /** Detailed per-question analysis array */
  questionAnalysis?: QuestionAnalysis[];
  status: "pending" | "in-progress" | "completed";
  createdAt: string; 
  focusArea?: string;
  score?: number;
  feedbackSummary?: string;
  feedbackDetail?: string;
  strengths?: string[];
  improvements?: string[];
  transcriptSummary?: string;
}

export interface CreateInterviewResult {
  success: boolean;
  message: string;
  interviewId?: string;
}

// Generate Questions via Gemini

async function generateQuestions(
  role: string,
  type: string,
  difficulty: string,
  count: number,
  focusArea: string
): Promise<InterviewQuestion[]> {
  const response = await fetch("/api/gemini/questions", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ role, type, difficulty, count, focusArea }),
  });

  if (!response.ok) {
    const data = (await response.json().catch(() => null)) as
      | { error?: string }
      | null;
    throw new Error(data?.error ?? "Failed to generate questions");
  }

  const data = (await response.json()) as { questions: string[] };
  const parsed = data?.questions;

  if (!Array.isArray(parsed)) {
    throw new Error("Gemini API route did not return a valid questions array");
  }

  return parsed.slice(0, count).map((questionText: string, i: number) => ({
    id: `q-${i + 1}`,
    text: questionText,
    userAnswer: "",
    rating: "",
    feedback: "",
  }));
}

// Create Interview

export async function createInterview(
  userId: string,
  role: string,
  type: string,
  difficulty: string,
  numQuestions: number,
  focusArea: string
): Promise<CreateInterviewResult> {
  try {
    const questions = await generateQuestions(
      role,
      type,
      difficulty,
      numQuestions,
      focusArea
    );
    const ref = doc(collection(db, "interviews"));

    await setDoc(ref, {
      id: ref.id,
      userId,
      role,
      type,
      difficulty,
      focusArea,
      numQuestions,
      questions,
      status: "pending",
      createdAt: new Date().toISOString(),
    });

    return {
      success: true,
      message: "Interview created successfully!",
      interviewId: ref.id,
    };
  } catch (error) {
    console.error("createInterview error:", error);
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";
    return {
      success: false,
      message: `Failed to create interview: ${errorMessage}`,
    };
  }
}

/**
 * Parses interview transcript to extract candidate answers for each question
 * if candidate answers were not explicitly stored in questions array.
 */
export function parseQAPairsFromTranscript(
  questions: InterviewQuestion[],
  transcriptSummary?: string
): InterviewQuestion[] {
  if (!questions || questions.length === 0) return [];
  if (!transcriptSummary || !transcriptSummary.trim()) {
    return questions;
  }

  const lines = transcriptSummary.split("\n").map((l) => l.trim()).filter(Boolean);
  const questionAnswers: string[] = new Array(questions.length).fill("");
  let currentQIndex = 0;

  for (const line of lines) {
    const isInterviewer =
      line.startsWith("Interviewer:") ||
      line.startsWith("Interviewer: ") ||
      /^Q\d+:/.test(line);

    const isCandidate =
      line.startsWith("You:") ||
      line.startsWith("You: ") ||
      line.startsWith("Candidate:") ||
      line.startsWith("Candidate: ") ||
      line.startsWith("User:") ||
      line.startsWith("User: ") ||
      /^A\d+:/.test(line);

    if (isInterviewer) {
      const lowerLine = line.toLowerCase();
      for (let i = 0; i < questions.length; i++) {
        const qClean = questions[i].text.toLowerCase().replace(/[^a-z0-9]/g, "");
        const lineClean = lowerLine.replace(/[^a-z0-9]/g, "");
        if (qClean.length > 10 && lineClean.includes(qClean.slice(0, 20))) {
          currentQIndex = i;
          break;
        }
      }
    } else if (isCandidate) {
      const cleanText = line.replace(/^(You|Candidate|User|A\d+):\s*/i, "").trim();
      if (cleanText) {
        if (questionAnswers[currentQIndex]) {
          questionAnswers[currentQIndex] += " " + cleanText;
        } else {
          questionAnswers[currentQIndex] = cleanText;
        }
      }
    }
  }

  return questions.map((q, i) => {
    const existingAnswer = q.userAnswer?.trim();
    const extractedAnswer = questionAnswers[i]?.trim();
    const finalAnswer =
      existingAnswer && existingAnswer !== ""
        ? existingAnswer
        : extractedAnswer || "";

    return {
      ...q,
      userAnswer: finalAnswer,
    };
  });
}

/**
 * Normalizes raw Firestore `questions` data into strongly typed `InterviewQuestion[]`.
 * Supports legacy formats (array of strings) and current format (array of InterviewQuestion objects).
 * Automatically extracts candidate answers from transcript if missing.
 */
export function normalizeQuestions(
  rawQuestions: unknown,
  transcriptSummary?: string
): InterviewQuestion[] {
  if (!Array.isArray(rawQuestions)) return [];

  const parsed: InterviewQuestion[] = rawQuestions.map((q, i) => {
    if (typeof q === "string") {
      return { id: `q-${i + 1}`, text: q, userAnswer: "", rating: "", feedback: "" };
    }
    if (typeof q === "object" && q !== null) {
      const qObj = q as Record<string, unknown>;
      return {
        id: String(qObj.id ?? `q-${i + 1}`),
        text: String(qObj.text ?? ""),
        userAnswer: String(qObj.userAnswer ?? ""),
        rating: String(qObj.rating ?? ""),
        feedback: String(qObj.feedback ?? ""),
      };
    }
    return { id: `q-${i + 1}`, text: "", userAnswer: "", rating: "", feedback: "" };
  });

  return parseQAPairsFromTranscript(parsed, transcriptSummary);
}

// Get Single Interview

export async function getInterview(id: string): Promise<Interview | null> {
  try {
    const snap = await getDoc(doc(db, "interviews", id));
    if (!snap.exists()) return null;

    const data = snap.data();
    const questions = normalizeQuestions(data.questions, data.transcriptSummary);

    return {
      id: snap.id,
      ...data,
      questions,
      createdAt: normalizeDate(data.createdAt),
      status: data.status ?? "pending",
      numQuestions: data.numQuestions ?? questions.length ?? 0,
      questionAnalysis: Array.isArray(data.questionAnalysis) ? data.questionAnalysis : [],
    } as Interview;
  } catch (error) {
    console.error("getInterview error:", error);
    return null;
  }
}

// Get All Interviews for a User

export async function getUserInterviews(userId: string): Promise<Interview[]> {
  try {
    let snapshot;

    try {
      
      const q = query(
        collection(db, "interviews"),
        where("userId", "==", userId),
        orderBy("createdAt", "desc")
      );
      snapshot = await getDocs(q);
    } catch {
      const fallbackQuery = query(
        collection(db, "interviews"),
        where("userId", "==", userId)
      );
      snapshot = await getDocs(fallbackQuery);

      const docs = snapshot.docs
        .map((docSnap) => {
          const data = docSnap.data();
          const questions = normalizeQuestions(data.questions, data.transcriptSummary);
          return {
            id: docSnap.id,
            ...data,
            questions,
            createdAt: normalizeDate(data.createdAt),
            status: data.status ?? "pending",
            numQuestions: data.numQuestions ?? questions.length ?? 0,
            questionAnalysis: Array.isArray(data.questionAnalysis) ? data.questionAnalysis : [],
          } as Interview;
        })
        .sort(
          (a, b) =>
            new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
        );

      return docs;
    }

    return snapshot.docs.map((docSnap) => {
      const data = docSnap.data();
      const questions = normalizeQuestions(data.questions, data.transcriptSummary);
      return {
        id: docSnap.id,
        ...data,
        questions,
        createdAt: normalizeDate(data.createdAt),
        status: data.status ?? "pending",
        numQuestions: data.numQuestions ?? questions.length ?? 0,
        questionAnalysis: Array.isArray(data.questionAnalysis) ? data.questionAnalysis : [],
      } as Interview;
    });
  } catch (error) {
    console.error("getUserInterviews error:", error);
    return [];
  }
}

// Update Interview Status

export async function updateInterviewStatus(
  interviewId: string,
  status: "pending" | "in-progress" | "completed"
): Promise<void> {
  try {
    await updateDoc(doc(db, "interviews", interviewId), { status });
  } catch (error) {
    console.error("updateInterviewStatus error:", error);
  }
}

/**
 * Payload interface for saving feedback data to Firebase Firestore.
 * Now includes updated questions array with user answers and per-question analysis.
 */
export interface InterviewFeedbackPayload {
  score: number;
  summary: string;
  detailedFeedback: string;
  strengths: string[];
  improvements: string[];
  transcriptSummary: string;
  /** Questions array enriched with candidate answers, rating, and feedback */
  questions?: InterviewQuestion[];
  /** Per-question analysis array */
  questionAnalysis?: QuestionAnalysis[];
}

/**
 * Persists complete interview feedback, overall evaluation scores, and per-question
 * candidate answers into the corresponding Firebase Firestore interview document.
 * 
 * @param interviewId Unique Firestore document ID for the interview
 * @param payload Object containing evaluation metrics, candidate answers, and question analysis
 */
export async function saveInterviewFeedback(
  interviewId: string,
  payload: InterviewFeedbackPayload
): Promise<void> {
  try {
    const updateData: Record<string, unknown> = {
      score: payload.score,
      feedbackSummary: payload.summary,
      feedbackDetail: payload.detailedFeedback,
      strengths: payload.strengths,
      improvements: payload.improvements,
      transcriptSummary: payload.transcriptSummary,
      status: "completed",
    };

    // Store updated questions with candidate answers if provided
    if (payload.questions && payload.questions.length > 0) {
      updateData.questions = payload.questions;
    }

    // Store detailed per-question analysis if provided
    if (payload.questionAnalysis && payload.questionAnalysis.length > 0) {
      updateData.questionAnalysis = payload.questionAnalysis;
    }

    await updateDoc(doc(db, "interviews", interviewId), updateData);
  } catch (error) {
    console.error("saveInterviewFeedback error:", error);
    throw error;
  }
}

function normalizeDate(value: unknown): string {
  if (!value) return new Date().toISOString();
  if (typeof value === "string") return value;
  if (value instanceof Date) return value.toISOString();
  if (value instanceof Timestamp) return value.toDate().toISOString();
  if (typeof value === "object" && "toDate" in value) {
    return (value as { toDate: () => Date }).toDate().toISOString();
  }
  return new Date().toISOString();
}

// Format Date for Display

export function formatInterviewDate(isoString: string): string {
  try {
    return new Date(isoString).toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  } catch {
    return "Unknown date";
  }
}

// Delete Interview

export async function deleteInterview(interviewId: string): Promise<boolean> {
  try {
    await deleteDoc(doc(db, "interviews", interviewId));
    return true;
  } catch (error) {
    console.error("deleteInterview error:", error);
    return false;
  }
}
